global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yaml

scrape_configs:
  - job_name: api
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:3001']

  - job_name: blackbox-readyz
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - http://host.docker.internal:3001/readyz
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

