name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install deps
        working-directory: backend
        run: npm ci

      - name: Lint
        working-directory: backend
        run: npm run lint

      - name: Test (mit Coverage)
        working-directory: backend
        run: npm test --silent -- --coverage --ci

      - name: Build
        working-directory: backend
        run: npm run build

      - name: Coverage hochladen (Artefakt)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: backend/coverage
          if-no-files-found: ignore
          retention-days: 7

  openapi-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Lint OpenAPI spec (Redocly)
        run: npx --yes @redocly/cli@latest lint docs/openapi.yaml
