name: commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Commitlint
        uses: wagoid/commitlint-github-action@e399437c83a8cc31c2760f7698154fd084061743 # v5
        with:
          configFile: commitlint.config.js

