name: contract-tests

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  lint-openapi:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=512
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Bundle OpenAPI (json)
        run: npx --yes swagger-cli@latest bundle -t json docs/openapi.yaml -o docs/openapi.bundled.json
      - name: Lint OpenAPI (Redocly)
        run: npx --yes @redocly/cli@latest lint docs/openapi.yaml --format=stylish
      - name: Upload bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: openapi-bundle
          path: docs/openapi.bundled.json

  prism-mock:
    needs: [lint-openapi]
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=512
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi-bundle
          path: docs
      - name: Start Prism mock (background) and probe
        shell: bash
        run: |
          set -euo pipefail
          npx --yes @stoplight/prism-cli@latest mock docs/openapi.bundled.json --port 4010 --host 127.0.0.1 > prism.log 2>&1 &
          echo $! > prism.pid
          for i in $(seq 1 20); do
            if curl -fsS http://127.0.0.1:4010/ >/dev/null; then
              echo "Prism mock is up"; break; fi
            sleep 2
          done
          # stop mock (this job only validates it can start)
          kill -TERM "$(cat prism.pid)" || true
      - name: Upload Prism log
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: prism-log
          path: prism.log

  dredd-run:
    needs: [lint-openapi]
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max-old-space-size=512
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Download bundle artifact
        uses: actions/download-artifact@v4
        with:
          name: openapi-bundle
          path: docs
      - name: Start Prism mock (background)
        shell: bash
        run: |
          set -euo pipefail
          npx --yes @stoplight/prism-cli@latest mock docs/openapi.bundled.json --port 4010 --host 127.0.0.1 > prism.log 2>&1 &
          echo $! > prism.pid
          for i in $(seq 1 20); do
            if curl -fsS http://127.0.0.1:4010/ >/dev/null; then
              echo "Prism mock is up"; break; fi
            sleep 2
          done
      - name: Run Dredd (inline errors)
        shell: bash
        run: |
          set -euo pipefail
          npx --yes dredd@14 \
            --path=docs/openapi.bundled.json \
            --endpoint=http://127.0.0.1:4010 \
            --inline-errors --color > reports/dredd-run.log 2>&1 || true
      - name: Stop Prism (always)
        if: ${{ always() }}
        run: |
          kill -TERM "$(cat prism.pid)" 2>/dev/null || true
      - name: Upload artifacts (bundle + logs)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: contract-tests-artifacts
          path: |
            docs/openapi.bundled.json
            prism.log
            reports/**/*.log
