name: docker-release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract tag
        id: meta
        run: |
          TAG="${GITHUB_REF_NAME}"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          echo "lower_repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.lower_repo }}:${{ steps.meta.outputs.tag }}
            ghcr.io/${{ steps.meta.outputs.lower_repo }}:latest

      - name: Trivy Image Scan (GHCR tag)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ghcr.io/${{ steps.meta.outputs.lower_repo }}:${{ steps.meta.outputs.tag }}
          format: sarif
          output: trivy-image.sarif
          ignore-unfixed: true
          vuln-type: 'os,library'

      - name: Upload Trivy SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-image.sarif

      - name: SBOM for image (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ steps.meta.outputs.lower_repo }}:${{ steps.meta.outputs.tag }}
          artifact-name: sbom-image-${{ steps.meta.outputs.tag }}
